name: Update latest posts

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - .github/workflows/blog-posts.yml

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://log4me.dev/rss.xml,https://qiita.com/phper_sugiyama/feed.atom"
          max_post_count: 5
